theme: jekyll-theme-cayman
title: 2022 IEEE World Congress on Computational Intelligence (WCCI)
description: Special Session on Computational intelligence for industrial sustainability (CIIS)
layout: page
